### ISSUE TITLE
Selinux policy

### ISSUE THREAD

**Issue by Moyster** [AllviewDevelopment/android_kernel_mediatek_mt6795#1]
You should start again, first patch your kernel up to 3.10.102 / 103 and then patches selinux, it'll be easier for you to cherry-pick without conflicts, look here for reference :
https://github.com/Moyster/android_kernel_m2note/commits/lp-5.1/security

Depending on how well the commits were done, it might applies fine in disorder but it's best for you to have the cleanest sources.

Also, you missed a few commits regarding selinux still, I don't see this commit for instance : 
https://github.com/Moyster/android_kernel_m2note/commit/b21cc87c6a6f592239f3a3ef06ec9f755fefa75c

Start fresh, add my kernel as a remote, then start cherry-picking, most of the conflicts should be related to defconfigs (because mine is named cm_m2note_defconfig and not whatever_allview_defconfig) same applies to commits named "regen defconfig".
There's a bit to learn here, first Git ;) then a bit of how kernels are made and you're gonna need to regen your defconfig as you bring your kernel up to higher versions so learning a bit about how to configure a kernel :)

Think of this as a puzzle and you need to figure how to pile the pieces together :)

Here's another protip: "git cherry-pick 123abc^..456dec" is how you would ask git to cherry-pick every commits from point A to point B. Look thru my commits history and start importing from commit 3.10.72/73 to 3.10.xyz, small or big steps are up to you if you want to be sure you didn't make mistakes or if you want (and you should) to be a prudent dev and do test (compile / clean / boots).

Good luck :)

**Comment by Moyster** [comment]
@bemolxd seems to be going well :+1:

**Comment by bemolxd** [comment]
Yes, it is! Gonna close it for now. Thank you!
